# Generated by Django 5.2.4 on 2025-07-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='resume_data_table',
        ),
    ]
